package br.com.conductor.awy.tela;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abraao
 */
public class Support  extends javax.swing.JFrame  {

    /**
     * Creates new form Support
     */
    public Support() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBy = new javax.swing.JButton();
        btCall = new javax.swing.JButton();
        btEmployee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(580, 420));
        setMinimumSize(new java.awt.Dimension(580, 420));
        setName(""); // NOI18N
        getContentPane().setLayout(null);

        btBy.setIcon(new javax.swing.ImageIcon("/home/abraao/NetBeansProjects/awy-mavenNetBeans/image/iconEmployees.png")); // NOI18N
        btBy.setText("Créditos ");
        btBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btByActionPerformed(evt);
            }
        });
        getContentPane().add(btBy);
        btBy.setBounds(210, 280, 230, 60);

        btCall.setIcon(new javax.swing.ImageIcon("/home/abraao/NetBeansProjects/awy-mavenNetBeans/image/iconContact.png")); // NOI18N
        btCall.setText("Entrar em contato com o suporte");
        btCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCallActionPerformed(evt);
            }
        });
        getContentPane().add(btCall);
        btCall.setBounds(150, 90, 360, 70);

        btEmployee.setIcon(new javax.swing.ImageIcon("/home/abraao/NetBeansProjects/awy-mavenNetBeans/image/iconPeoplesearcher.png")); // NOI18N
        btEmployee.setText("Entrar em contato com um funcionário ");
        btEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btEmployee);
        btEmployee.setBounds(150, 170, 360, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/abraao/NetBeansProjects/awy-mavenNetBeans/image/backgroundSupport.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCallActionPerformed
        // TODO add your handling code here:
       String strDefaultCall= "";
        String Ccpf = String.valueOf(JOptionPane.showInputDialog("Digite seu o telefone: ",strDefaultCall));
    }//GEN-LAST:event_btCallActionPerformed

    private void btByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btByActionPerformed
        // TODO add your handling code here:
        String strTeam = "Abraão Állysson\n"+"Wellton Thyago\n"+ "Yuri Gouveia";
        JOptionPane.showMessageDialog(this, strTeam, "Equipe",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btByActionPerformed

    private void btEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmployeeActionPerformed
        // TODO add your handling code here:
         String strInfo = "Aguarde, por favor..."+ "\n funcionario está indo ao seu ecnontro";
        JOptionPane.showMessageDialog(this, strInfo, "Informação",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btEmployeeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBy;
    private javax.swing.JButton btCall;
    private javax.swing.JButton btEmployee;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
